<a href="https://colab.research.google.com/github/ctrctr/2020MachineLearning-preper/blob/master/Numpy_useage.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Array(数组)
* rank（数组的维数）

In [0]:
import numpy as np

In [0]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [0]:
type(a)  #a的数据类型

numpy.ndarray

In [0]:
a.shape #(5, )不确定5是行，还是列，使用reshape的方法，确定行 or 列

(5,)

In [0]:
a = a.reshape((1,-1))    #-1 是占位符，实际上是a.shape里的5/1
a.shape

(1, 5)

In [0]:
a

array([[1, 2, 3, 4, 5]])

In [0]:
a = a.reshape((5,-1))
a.shape

(5, 1)

In [0]:
a

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [0]:
b= np.array([1,2,3,4,5,6])

In [0]:
b

array([1, 2, 3, 4, 5, 6])

In [0]:
b = b.reshape(3,-1)          #-1 是占位符，实际上是a.shape里的6/3
b.shape

(3, 2)

In [0]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
a[2,0]

3

In [0]:
b[2,0] = 55       #array中替换某个item的方法
b

array([[ 1,  2],
       [ 3,  4],
       [55,  6]])

## 创建数组的函数
1. zeros  创建全是0的数组
2. ones  创建全是1的数组 
3. full  创建全是n的数组
4. eys  创建单位矩阵
[1,0,0]
[0,1,0]
[0,0,1]
5. random.random 创建随机数组，数组中的元素全部都是（0，1）的随机数

In [0]:
c = np.zeros((2,3))  # 一定要加（），否则报错（亲犯）


In [0]:
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [0]:
d = np.ones((3,3))

In [0]:
d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [0]:
e = np.full((2,2),3)

In [0]:
e

array([[3, 3],
       [3, 3]])

In [0]:
f = np.eye(3)

In [0]:
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [0]:
g = np.random.random((2,3))

In [0]:
g

array([[0.75512106, 0.40463419, 0.9990436 ],
       [0.36205151, 0.40731982, 0.06070362]])

# indexing

In [0]:
h = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
h

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [0]:
i = h[-2:,1:3]   
i

array([[ 6,  7],
       [10, 11]])

-2 倒数第二行 :表示从倒数第二行一直到最后（从倒数第二行到倒数第n行）

1：3 从第一列开始，往后数（3-1）列

In [0]:
i.shape

(2, 2)

In [0]:
j = h[2,3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [0]:
j.shape

()

In [0]:
k = h[1:,1:3]
k

array([[ 6,  7],
       [10, 11]])

In [0]:
k.shape
h

array([[ 1, 32,  3,  4],
       [ 5, 36,  7,  8],
       [ 9, 40, 11, 12]])

## 需求：为h的每行的第二个元素加10

In [0]:
h[[0,1,2],[1,1,1]] += 10                      #比较笨的方法
h

array([[ 1, 12,  3,  4],
       [ 5, 16,  7,  8],
       [ 9, 20, 11, 12]])

In [0]:
h[np.arange(3),1] +=10                      # 第二种方法   np.arange(3,7)=>[3,4,5,6]
h

array([[ 1, 22,  3,  4],
       [ 5, 26,  7,  8],
       [ 9, 30, 11, 12]])

## 需求：获取数组中所有大于10的数

In [0]:
result_index = h>10
result_index

array([[False,  True, False, False],
       [False,  True, False, False],
       [False,  True,  True,  True]])

In [0]:
h[result_index]

array([22, 26, 30, 11, 12])

In [0]:
h[h>10]

array([22, 26, 30, 11, 12])

  # 元素的数据类型    

In [0]:
l = np.array([1,2])
l

array([1, 2])

In [0]:
l.dtype

dtype('int32')

In [0]:
m = np.array([1.1,2.2,3])

In [0]:
m.dtype

dtype('float64')

##  需求：只取数组中元素的整数部分

In [0]:
o = np.array([1.1,2.2],dtype=np.int64)
o

array([1, 2], dtype=int64)

In [0]:
p = np.array(m,dtype=np.int64)
p

array([1, 2, 3], dtype=int64)

# 矩阵运算与运算常用函数

In [0]:
w = np.array([[2,3],
             [4,5]])
w

array([[2, 3],
       [4, 5]])

In [0]:
y = np.array([[1,2],
            [3,4]])

array([[1, 2],
       [3, 4]])

In [0]:
z = np.array([[1,2,3],
             [4,5,6]])
z

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
w+y

array([[3, 5],
       [7, 9]])

In [0]:
np.add(w,y)                 # The same with w+y

array([[3, 5],
       [7, 9]])

In [0]:
w-y

array([[1, 1],
       [1, 1]])

In [0]:
np.subtract(w,y)            # The same with w-y

array([[1, 1],
       [1, 1]])

In [0]:
w*2

array([[ 4,  6],
       [ 8, 10]])

In [0]:
np.multiply(w,2)            # The same with w*2

array([[ 4,  6],
       [ 8, 10]])

In [0]:
np.multiply(w,y)           # multiply 可以用在行列相等的乘法运算中

array([[ 2,  6],
       [12, 20]])

In [0]:
w/2

array([[1. , 1.5],
       [2. , 2.5]])

In [0]:
np.divide(w,2)             # divide 和 multiply 类似

array([[1. , 1.5],
       [2. , 2.5]])

In [0]:
np.sqrt(w)                 # 开方操作

array([[1.41421356, 1.73205081],
       [2.        , 2.23606798]])

In [0]:
np.dot(y,z)                #矩阵乘法操作

array([[ 9, 12, 15],
       [19, 26, 33]])

## 常用函数
1. sum 求和
2. mean  求平均
3. uniform  随机生成，搭配random使用
3. tile   重复  
np.tile(w,(1,2))： 将W看成一个item，在行上重复1次，在列上重复2次
4. argsort 排序（默认按行排序）
5. transpose 转置 同T

In [0]:
w

array([[2, 3],
       [4, 5]])

In [0]:
np.sum(w)                           # sum 求和

14

In [0]:
np.sum(w,axis=0)                    #当axis等于0，看列；

array([6, 8])

In [0]:
np.mean(w)                          # mean求平均

3.5

In [0]:
np.mean(w,axis=1)                  # 当axis等一一，看行

array([2.5, 4.5])

In [0]:
np.random.uniform(2,3)           #随机生成（2，3）的随机数；小数

2.0797884863585296

In [0]:
np.tile(w,(1,2))                 # 将W看成一个item，在行上重复1次，在列上重复2次

array([[2, 3, 2, 3],
       [4, 5, 4, 5]])

In [0]:
z

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
np.argsort(z)                    # 将数组中的元素按照每一行从小到大排序,返回下标

array([[0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [0]:
z.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1]], dtype=int64)

In [0]:
z.T                            # 转置

array([[1, 4],
       [2, 5],
       [3, 6]])

In [0]:
np.transpose(z)

array([[1, 4],
       [2, 5],
       [3, 6]])

# Numpy 广播特性

可以将不同“维度”的数组自动转成想同纬度进行计算
强调维度，不是行数列数

In [0]:
y=np.array([[1,2,3],
          [4,5,6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
z2=np.array([1,2,3])
z2

array([1, 2, 3])

In [0]:
y+z2

array([[2, 4, 6],
       [5, 7, 9]])